databases:
  - name: aa-educates-db
    databaseName: aa_educates
    user: aa_educates_user
    plan: free

services:
  - type: web
    name: aa-educates-backend
    runtime: python
    plan: free
    buildCommand: "./backend/build.sh"
    startCommand: "cd backend && gunicorn backend.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: aa-educates-db
          property: connectionString
      - key: FRONTEND_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
